### ISSUE TITLE
Proposed changes for FieldValidator.java

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/browser-calls-spark#1]
I like the shape of this class, but I guess there is some room for improvement here.

1. Based on the implementation looks like the intention of this class is to validate a group of fields, not just one, so that, would you mind renaming it to `FieldsValidator`?

2. [Here](https://github.com/TwilioDevEd/browser-calls-spark/blob/7343c8be0f254308ec034bdb866c97883facb366/src/main/java/com/twilio/browsercalls/lib/FieldValidator.java#L34-L38) you can take advantage of `filter`,  this is an alternative implementation:

   ```java
   List<String> messages = mappedValues.stream()
      .filter(value -> !value.equals(""))
      .collect(Collectors.toList());
   ```

3. [This](https://github.com/TwilioDevEd/browser-calls-spark/blob/7343c8be0f254308ec034bdb866c97883facb366/src/main/java/com/twilio/browsercalls/lib/FieldValidator.java#L42-L46) looks redundant, since you're using a comparison (_it returns a `Boolean`_) to return the negation of that comparison.

   ```java
   // If there are messages, then it is not valid.
   if (messages.size() > 0) {
     return false;
   } else {
     return true;
   }
   ```
   I guess this one can be wrote as:

   ```java
   return messages.count() <= 0;
   ```

   Or even better:

   ```java
   return !messages.isEmpty();
   ```

What do you think?

**Comment by mcelicalderon** [comment]
Changes already applied to the application.
